#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebThietBi.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ThietBiDienTu")]
	public partial class ThietBiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAnhSanPham(AnhSanPham instance);
    partial void UpdateAnhSanPham(AnhSanPham instance);
    partial void DeleteAnhSanPham(AnhSanPham instance);
    partial void InsertHoaDonBan(HoaDonBan instance);
    partial void UpdateHoaDonBan(HoaDonBan instance);
    partial void DeleteHoaDonBan(HoaDonBan instance);
    partial void InsertKhuyenMai(KhuyenMai instance);
    partial void UpdateKhuyenMai(KhuyenMai instance);
    partial void DeleteKhuyenMai(KhuyenMai instance);
    partial void InsertLoaiSanPham(LoaiSanPham instance);
    partial void UpdateLoaiSanPham(LoaiSanPham instance);
    partial void DeleteLoaiSanPham(LoaiSanPham instance);
    partial void InsertMauSac(MauSac instance);
    partial void UpdateMauSac(MauSac instance);
    partial void DeleteMauSac(MauSac instance);
    partial void InsertReview(Review instance);
    partial void UpdateReview(Review instance);
    partial void DeleteReview(Review instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    partial void InsertTaiKhoanKhachHang(TaiKhoanKhachHang instance);
    partial void UpdateTaiKhoanKhachHang(TaiKhoanKhachHang instance);
    partial void DeleteTaiKhoanKhachHang(TaiKhoanKhachHang instance);
    #endregion
		
		public ThietBiDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ThietBiDienTuConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ThietBiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThietBiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThietBiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThietBiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AnhSanPham> AnhSanPhams
		{
			get
			{
				return this.GetTable<AnhSanPham>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this.GetTable<ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonBan> HoaDonBans
		{
			get
			{
				return this.GetTable<HoaDonBan>();
			}
		}
		
		public System.Data.Linq.Table<KhuyenMai> KhuyenMais
		{
			get
			{
				return this.GetTable<KhuyenMai>();
			}
		}
		
		public System.Data.Linq.Table<LoaiSanPham> LoaiSanPhams
		{
			get
			{
				return this.GetTable<LoaiSanPham>();
			}
		}
		
		public System.Data.Linq.Table<MauSac> MauSacs
		{
			get
			{
				return this.GetTable<MauSac>();
			}
		}
		
		public System.Data.Linq.Table<MauSacSanPham> MauSacSanPhams
		{
			get
			{
				return this.GetTable<MauSacSanPham>();
			}
		}
		
		public System.Data.Linq.Table<Review> Reviews
		{
			get
			{
				return this.GetTable<Review>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoanKhachHang> TaiKhoanKhachHangs
		{
			get
			{
				return this.GetTable<TaiKhoanKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<ThamGiaKhuyenMai> ThamGiaKhuyenMais
		{
			get
			{
				return this.GetTable<ThamGiaKhuyenMai>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinCuaHang> ThongTinCuaHangs
		{
			get
			{
				return this.GetTable<ThongTinCuaHang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnhSanPham")]
	public partial class AnhSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Anh;
		
		private string _TenAnh;
		
		private string _ID_SanPham;
		
		private EntityRef<SanPham> _SanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AnhChanging(string value);
    partial void OnID_AnhChanged();
    partial void OnTenAnhChanging(string value);
    partial void OnTenAnhChanged();
    partial void OnID_SanPhamChanging(string value);
    partial void OnID_SanPhamChanged();
    #endregion
		
		public AnhSanPham()
		{
			this._SanPham = default(EntityRef<SanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Anh", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Anh
		{
			get
			{
				return this._ID_Anh;
			}
			set
			{
				if ((this._ID_Anh != value))
				{
					this.OnID_AnhChanging(value);
					this.SendPropertyChanging();
					this._ID_Anh = value;
					this.SendPropertyChanged("ID_Anh");
					this.OnID_AnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenAnh", DbType="Char(30) NOT NULL", CanBeNull=false)]
		public string TenAnh
		{
			get
			{
				return this._TenAnh;
			}
			set
			{
				if ((this._TenAnh != value))
				{
					this.OnTenAnhChanging(value);
					this.SendPropertyChanging();
					this._TenAnh = value;
					this.SendPropertyChanged("TenAnh");
					this.OnTenAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SanPham", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ID_SanPham
		{
			get
			{
				return this._ID_SanPham;
			}
			set
			{
				if ((this._ID_SanPham != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SanPhamChanging(value);
					this.SendPropertyChanging();
					this._ID_SanPham = value;
					this.SendPropertyChanged("ID_SanPham");
					this.OnID_SanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_AnhSanPham", Storage="_SanPham", ThisKey="ID_SanPham", OtherKey="ID_SanPham", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.AnhSanPhams.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.AnhSanPhams.Add(this);
						this._ID_SanPham = value.ID_SanPham;
					}
					else
					{
						this._ID_SanPham = default(string);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHoaDon")]
	public partial class ChiTietHoaDon
	{
		
		private string _ID_HDB;
		
		private string _ID_SanPham;
		
		private int _SoLuong;
		
		private int _DonGia;
		
		public ChiTietHoaDon()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HDB", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ID_HDB
		{
			get
			{
				return this._ID_HDB;
			}
			set
			{
				if ((this._ID_HDB != value))
				{
					this._ID_HDB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SanPham", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ID_SanPham
		{
			get
			{
				return this._ID_SanPham;
			}
			set
			{
				if ((this._ID_SanPham != value))
				{
					this._ID_SanPham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Int NOT NULL")]
		public int DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this._DonGia = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonBan")]
	public partial class HoaDonBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_HDB;
		
		private System.DateTime _NgayLapHDB;
		
		private string _ID_KhachHang;
		
		private System.Nullable<bool> _TrangThai;
		
		private System.Nullable<int> _ThanhTien;
		
		private EntityRef<TaiKhoanKhachHang> _TaiKhoanKhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_HDBChanging(string value);
    partial void OnID_HDBChanged();
    partial void OnNgayLapHDBChanging(System.DateTime value);
    partial void OnNgayLapHDBChanged();
    partial void OnID_KhachHangChanging(string value);
    partial void OnID_KhachHangChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    partial void OnThanhTienChanging(System.Nullable<int> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public HoaDonBan()
		{
			this._TaiKhoanKhachHang = default(EntityRef<TaiKhoanKhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HDB", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_HDB
		{
			get
			{
				return this._ID_HDB;
			}
			set
			{
				if ((this._ID_HDB != value))
				{
					this.OnID_HDBChanging(value);
					this.SendPropertyChanging();
					this._ID_HDB = value;
					this.SendPropertyChanged("ID_HDB");
					this.OnID_HDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapHDB", DbType="DateTime NOT NULL")]
		public System.DateTime NgayLapHDB
		{
			get
			{
				return this._NgayLapHDB;
			}
			set
			{
				if ((this._NgayLapHDB != value))
				{
					this.OnNgayLapHDBChanging(value);
					this.SendPropertyChanging();
					this._NgayLapHDB = value;
					this.SendPropertyChanged("NgayLapHDB");
					this.OnNgayLapHDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KhachHang", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ID_KhachHang
		{
			get
			{
				return this._ID_KhachHang;
			}
			set
			{
				if ((this._ID_KhachHang != value))
				{
					if (this._TaiKhoanKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KhachHangChanging(value);
					this.SendPropertyChanging();
					this._ID_KhachHang = value;
					this.SendPropertyChanged("ID_KhachHang");
					this.OnID_KhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoanKhachHang_HoaDonBan", Storage="_TaiKhoanKhachHang", ThisKey="ID_KhachHang", OtherKey="ID_KhachHang", IsForeignKey=true)]
		public TaiKhoanKhachHang TaiKhoanKhachHang
		{
			get
			{
				return this._TaiKhoanKhachHang.Entity;
			}
			set
			{
				TaiKhoanKhachHang previousValue = this._TaiKhoanKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoanKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoanKhachHang.Entity = null;
						previousValue.HoaDonBans.Remove(this);
					}
					this._TaiKhoanKhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDonBans.Add(this);
						this._ID_KhachHang = value.ID_KhachHang;
					}
					else
					{
						this._ID_KhachHang = default(string);
					}
					this.SendPropertyChanged("TaiKhoanKhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuyenMai")]
	public partial class KhuyenMai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_KhuyenMai;
		
		private System.DateTime _ThoiGianBatDau;
		
		private System.DateTime _ThoiGianKetThuc;
		
		private int _GiamGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_KhuyenMaiChanging(string value);
    partial void OnID_KhuyenMaiChanged();
    partial void OnThoiGianBatDauChanging(System.DateTime value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.DateTime value);
    partial void OnThoiGianKetThucChanged();
    partial void OnGiamGiaChanging(int value);
    partial void OnGiamGiaChanged();
    #endregion
		
		public KhuyenMai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KhuyenMai", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_KhuyenMai
		{
			get
			{
				return this._ID_KhuyenMai;
			}
			set
			{
				if ((this._ID_KhuyenMai != value))
				{
					this.OnID_KhuyenMaiChanging(value);
					this.SendPropertyChanging();
					this._ID_KhuyenMai = value;
					this.SendPropertyChanged("ID_KhuyenMai");
					this.OnID_KhuyenMaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="DateTime NOT NULL")]
		public System.DateTime ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="Int NOT NULL")]
		public int GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiSanPham")]
	public partial class LoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_LoaiSanPham;
		
		private string _TenLoaiSanPham;
		
		private EntitySet<SanPham> _SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LoaiSanPhamChanging(string value);
    partial void OnID_LoaiSanPhamChanged();
    partial void OnTenLoaiSanPhamChanging(string value);
    partial void OnTenLoaiSanPhamChanged();
    #endregion
		
		public LoaiSanPham()
		{
			this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LoaiSanPham", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_LoaiSanPham
		{
			get
			{
				return this._ID_LoaiSanPham;
			}
			set
			{
				if ((this._ID_LoaiSanPham != value))
				{
					this.OnID_LoaiSanPhamChanging(value);
					this.SendPropertyChanging();
					this._ID_LoaiSanPham = value;
					this.SendPropertyChanged("ID_LoaiSanPham");
					this.OnID_LoaiSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiSanPham", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string TenLoaiSanPham
		{
			get
			{
				return this._TenLoaiSanPham;
			}
			set
			{
				if ((this._TenLoaiSanPham != value))
				{
					this.OnTenLoaiSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiSanPham = value;
					this.SendPropertyChanged("TenLoaiSanPham");
					this.OnTenLoaiSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSanPham_SanPham", Storage="_SanPhams", ThisKey="ID_LoaiSanPham", OtherKey="ID_LoaiSanPham")]
		public EntitySet<SanPham> SanPhams
		{
			get
			{
				return this._SanPhams;
			}
			set
			{
				this._SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.LoaiSanPham = this;
		}
		
		private void detach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.LoaiSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MauSac")]
	public partial class MauSac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_MauSac;
		
		private string _TenMauSac;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MauSacChanging(string value);
    partial void OnID_MauSacChanged();
    partial void OnTenMauSacChanging(string value);
    partial void OnTenMauSacChanged();
    #endregion
		
		public MauSac()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MauSac", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_MauSac
		{
			get
			{
				return this._ID_MauSac;
			}
			set
			{
				if ((this._ID_MauSac != value))
				{
					this.OnID_MauSacChanging(value);
					this.SendPropertyChanging();
					this._ID_MauSac = value;
					this.SendPropertyChanged("ID_MauSac");
					this.OnID_MauSacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMauSac", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TenMauSac
		{
			get
			{
				return this._TenMauSac;
			}
			set
			{
				if ((this._TenMauSac != value))
				{
					this.OnTenMauSacChanging(value);
					this.SendPropertyChanging();
					this._TenMauSac = value;
					this.SendPropertyChanged("TenMauSac");
					this.OnTenMauSacChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MauSacSanPham")]
	public partial class MauSacSanPham
	{
		
		private string _ID_MauSac;
		
		private string _ID_SanPham;
		
		public MauSacSanPham()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MauSac", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ID_MauSac
		{
			get
			{
				return this._ID_MauSac;
			}
			set
			{
				if ((this._ID_MauSac != value))
				{
					this._ID_MauSac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SanPham", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ID_SanPham
		{
			get
			{
				return this._ID_SanPham;
			}
			set
			{
				if ((this._ID_SanPham != value))
				{
					this._ID_SanPham = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Review")]
	public partial class Review : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_Review;
		
		private string _ID_SanPham;
		
		private string _ID_KhachHang;
		
		private System.Nullable<int> _Rating;
		
		private string _comment;
		
		private System.Nullable<System.DateTime> _Ngay_Review;
		
		private EntityRef<SanPham> _SanPham;
		
		private EntityRef<TaiKhoanKhachHang> _TaiKhoanKhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ReviewChanging(string value);
    partial void OnID_ReviewChanged();
    partial void OnID_SanPhamChanging(string value);
    partial void OnID_SanPhamChanged();
    partial void OnID_KhachHangChanging(string value);
    partial void OnID_KhachHangChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OnNgay_ReviewChanging(System.Nullable<System.DateTime> value);
    partial void OnNgay_ReviewChanged();
    #endregion
		
		public Review()
		{
			this._SanPham = default(EntityRef<SanPham>);
			this._TaiKhoanKhachHang = default(EntityRef<TaiKhoanKhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Review", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_Review
		{
			get
			{
				return this._ID_Review;
			}
			set
			{
				if ((this._ID_Review != value))
				{
					this.OnID_ReviewChanging(value);
					this.SendPropertyChanging();
					this._ID_Review = value;
					this.SendPropertyChanged("ID_Review");
					this.OnID_ReviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SanPham", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ID_SanPham
		{
			get
			{
				return this._ID_SanPham;
			}
			set
			{
				if ((this._ID_SanPham != value))
				{
					if (this._SanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SanPhamChanging(value);
					this.SendPropertyChanging();
					this._ID_SanPham = value;
					this.SendPropertyChanged("ID_SanPham");
					this.OnID_SanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KhachHang", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ID_KhachHang
		{
			get
			{
				return this._ID_KhachHang;
			}
			set
			{
				if ((this._ID_KhachHang != value))
				{
					if (this._TaiKhoanKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_KhachHangChanging(value);
					this.SendPropertyChanging();
					this._ID_KhachHang = value;
					this.SendPropertyChanged("ID_KhachHang");
					this.OnID_KhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
		public System.Nullable<int> Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this.OnRatingChanging(value);
					this.SendPropertyChanging();
					this._Rating = value;
					this.SendPropertyChanged("Rating");
					this.OnRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="NVarChar(200)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_Review", DbType="Date")]
		public System.Nullable<System.DateTime> Ngay_Review
		{
			get
			{
				return this._Ngay_Review;
			}
			set
			{
				if ((this._Ngay_Review != value))
				{
					this.OnNgay_ReviewChanging(value);
					this.SendPropertyChanging();
					this._Ngay_Review = value;
					this.SendPropertyChanged("Ngay_Review");
					this.OnNgay_ReviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_Review", Storage="_SanPham", ThisKey="ID_SanPham", OtherKey="ID_SanPham", IsForeignKey=true)]
		public SanPham SanPham
		{
			get
			{
				return this._SanPham.Entity;
			}
			set
			{
				SanPham previousValue = this._SanPham.Entity;
				if (((previousValue != value) 
							|| (this._SanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SanPham.Entity = null;
						previousValue.Reviews.Remove(this);
					}
					this._SanPham.Entity = value;
					if ((value != null))
					{
						value.Reviews.Add(this);
						this._ID_SanPham = value.ID_SanPham;
					}
					else
					{
						this._ID_SanPham = default(string);
					}
					this.SendPropertyChanged("SanPham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoanKhachHang_Review", Storage="_TaiKhoanKhachHang", ThisKey="ID_KhachHang", OtherKey="ID_KhachHang", IsForeignKey=true)]
		public TaiKhoanKhachHang TaiKhoanKhachHang
		{
			get
			{
				return this._TaiKhoanKhachHang.Entity;
			}
			set
			{
				TaiKhoanKhachHang previousValue = this._TaiKhoanKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoanKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoanKhachHang.Entity = null;
						previousValue.Reviews.Remove(this);
					}
					this._TaiKhoanKhachHang.Entity = value;
					if ((value != null))
					{
						value.Reviews.Add(this);
						this._ID_KhachHang = value.ID_KhachHang;
					}
					else
					{
						this._ID_KhachHang = default(string);
					}
					this.SendPropertyChanged("TaiKhoanKhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_SanPham;
		
		private string _TenSanPham;
		
		private int _TRONGLUONG;
		
		private string _NamSanXuat;
		
		private string _KichThuoc;
		
		private string _ID_LoaiSanPham;
		
		private string _MoTaChiTiet;
		
		private int _GIANHAP;
		
		private int _GIABAN;
		
		private int _SoLuongKho;
		
		private EntitySet<AnhSanPham> _AnhSanPhams;
		
		private EntitySet<Review> _Reviews;
		
		private EntityRef<LoaiSanPham> _LoaiSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SanPhamChanging(string value);
    partial void OnID_SanPhamChanged();
    partial void OnTenSanPhamChanging(string value);
    partial void OnTenSanPhamChanged();
    partial void OnTRONGLUONGChanging(int value);
    partial void OnTRONGLUONGChanged();
    partial void OnNamSanXuatChanging(string value);
    partial void OnNamSanXuatChanged();
    partial void OnKichThuocChanging(string value);
    partial void OnKichThuocChanged();
    partial void OnID_LoaiSanPhamChanging(string value);
    partial void OnID_LoaiSanPhamChanged();
    partial void OnMoTaChiTietChanging(string value);
    partial void OnMoTaChiTietChanged();
    partial void OnGIANHAPChanging(int value);
    partial void OnGIANHAPChanged();
    partial void OnGIABANChanging(int value);
    partial void OnGIABANChanged();
    partial void OnSoLuongKhoChanging(int value);
    partial void OnSoLuongKhoChanged();
    #endregion
		
		public SanPham()
		{
			this._AnhSanPhams = new EntitySet<AnhSanPham>(new Action<AnhSanPham>(this.attach_AnhSanPhams), new Action<AnhSanPham>(this.detach_AnhSanPhams));
			this._Reviews = new EntitySet<Review>(new Action<Review>(this.attach_Reviews), new Action<Review>(this.detach_Reviews));
			this._LoaiSanPham = default(EntityRef<LoaiSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SanPham", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_SanPham
		{
			get
			{
				return this._ID_SanPham;
			}
			set
			{
				if ((this._ID_SanPham != value))
				{
					this.OnID_SanPhamChanging(value);
					this.SendPropertyChanging();
					this._ID_SanPham = value;
					this.SendPropertyChanged("ID_SanPham");
					this.OnID_SanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSanPham", DbType="NVarChar(300)")]
		public string TenSanPham
		{
			get
			{
				return this._TenSanPham;
			}
			set
			{
				if ((this._TenSanPham != value))
				{
					this.OnTenSanPhamChanging(value);
					this.SendPropertyChanging();
					this._TenSanPham = value;
					this.SendPropertyChanged("TenSanPham");
					this.OnTenSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRONGLUONG", DbType="Int NOT NULL")]
		public int TRONGLUONG
		{
			get
			{
				return this._TRONGLUONG;
			}
			set
			{
				if ((this._TRONGLUONG != value))
				{
					this.OnTRONGLUONGChanging(value);
					this.SendPropertyChanging();
					this._TRONGLUONG = value;
					this.SendPropertyChanged("TRONGLUONG");
					this.OnTRONGLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSanXuat", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NamSanXuat
		{
			get
			{
				return this._NamSanXuat;
			}
			set
			{
				if ((this._NamSanXuat != value))
				{
					this.OnNamSanXuatChanging(value);
					this.SendPropertyChanging();
					this._NamSanXuat = value;
					this.SendPropertyChanged("NamSanXuat");
					this.OnNamSanXuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KichThuoc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KichThuoc
		{
			get
			{
				return this._KichThuoc;
			}
			set
			{
				if ((this._KichThuoc != value))
				{
					this.OnKichThuocChanging(value);
					this.SendPropertyChanging();
					this._KichThuoc = value;
					this.SendPropertyChanged("KichThuoc");
					this.OnKichThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LoaiSanPham", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ID_LoaiSanPham
		{
			get
			{
				return this._ID_LoaiSanPham;
			}
			set
			{
				if ((this._ID_LoaiSanPham != value))
				{
					if (this._LoaiSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LoaiSanPhamChanging(value);
					this.SendPropertyChanging();
					this._ID_LoaiSanPham = value;
					this.SendPropertyChanged("ID_LoaiSanPham");
					this.OnID_LoaiSanPhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaChiTiet", DbType="NVarChar(500)")]
		public string MoTaChiTiet
		{
			get
			{
				return this._MoTaChiTiet;
			}
			set
			{
				if ((this._MoTaChiTiet != value))
				{
					this.OnMoTaChiTietChanging(value);
					this.SendPropertyChanging();
					this._MoTaChiTiet = value;
					this.SendPropertyChanged("MoTaChiTiet");
					this.OnMoTaChiTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIANHAP", DbType="Int NOT NULL")]
		public int GIANHAP
		{
			get
			{
				return this._GIANHAP;
			}
			set
			{
				if ((this._GIANHAP != value))
				{
					this.OnGIANHAPChanging(value);
					this.SendPropertyChanging();
					this._GIANHAP = value;
					this.SendPropertyChanged("GIANHAP");
					this.OnGIANHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABAN", DbType="Int NOT NULL")]
		public int GIABAN
		{
			get
			{
				return this._GIABAN;
			}
			set
			{
				if ((this._GIABAN != value))
				{
					this.OnGIABANChanging(value);
					this.SendPropertyChanging();
					this._GIABAN = value;
					this.SendPropertyChanged("GIABAN");
					this.OnGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongKho", DbType="Int NOT NULL")]
		public int SoLuongKho
		{
			get
			{
				return this._SoLuongKho;
			}
			set
			{
				if ((this._SoLuongKho != value))
				{
					this.OnSoLuongKhoChanging(value);
					this.SendPropertyChanging();
					this._SoLuongKho = value;
					this.SendPropertyChanged("SoLuongKho");
					this.OnSoLuongKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_AnhSanPham", Storage="_AnhSanPhams", ThisKey="ID_SanPham", OtherKey="ID_SanPham")]
		public EntitySet<AnhSanPham> AnhSanPhams
		{
			get
			{
				return this._AnhSanPhams;
			}
			set
			{
				this._AnhSanPhams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_Review", Storage="_Reviews", ThisKey="ID_SanPham", OtherKey="ID_SanPham")]
		public EntitySet<Review> Reviews
		{
			get
			{
				return this._Reviews;
			}
			set
			{
				this._Reviews.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSanPham_SanPham", Storage="_LoaiSanPham", ThisKey="ID_LoaiSanPham", OtherKey="ID_LoaiSanPham", IsForeignKey=true)]
		public LoaiSanPham LoaiSanPham
		{
			get
			{
				return this._LoaiSanPham.Entity;
			}
			set
			{
				LoaiSanPham previousValue = this._LoaiSanPham.Entity;
				if (((previousValue != value) 
							|| (this._LoaiSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiSanPham.Entity = null;
						previousValue.SanPhams.Remove(this);
					}
					this._LoaiSanPham.Entity = value;
					if ((value != null))
					{
						value.SanPhams.Add(this);
						this._ID_LoaiSanPham = value.ID_LoaiSanPham;
					}
					else
					{
						this._ID_LoaiSanPham = default(string);
					}
					this.SendPropertyChanged("LoaiSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AnhSanPhams(AnhSanPham entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_AnhSanPhams(AnhSanPham entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
		
		private void attach_Reviews(Review entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = this;
		}
		
		private void detach_Reviews(Review entity)
		{
			this.SendPropertyChanging();
			entity.SanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoanKhachHang")]
	public partial class TaiKhoanKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_KhachHang;
		
		private string _HoTenKhachHang;
		
		private string _SDT_KhachHang;
		
		private string _DiaChi;
		
		private string _MatKhau;
		
		private EntitySet<HoaDonBan> _HoaDonBans;
		
		private EntitySet<Review> _Reviews;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_KhachHangChanging(string value);
    partial void OnID_KhachHangChanged();
    partial void OnHoTenKhachHangChanging(string value);
    partial void OnHoTenKhachHangChanged();
    partial void OnSDT_KhachHangChanging(string value);
    partial void OnSDT_KhachHangChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
		
		public TaiKhoanKhachHang()
		{
			this._HoaDonBans = new EntitySet<HoaDonBan>(new Action<HoaDonBan>(this.attach_HoaDonBans), new Action<HoaDonBan>(this.detach_HoaDonBans));
			this._Reviews = new EntitySet<Review>(new Action<Review>(this.attach_Reviews), new Action<Review>(this.detach_Reviews));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KhachHang", DbType="Char(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_KhachHang
		{
			get
			{
				return this._ID_KhachHang;
			}
			set
			{
				if ((this._ID_KhachHang != value))
				{
					this.OnID_KhachHangChanging(value);
					this.SendPropertyChanging();
					this._ID_KhachHang = value;
					this.SendPropertyChanged("ID_KhachHang");
					this.OnID_KhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenKhachHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTenKhachHang
		{
			get
			{
				return this._HoTenKhachHang;
			}
			set
			{
				if ((this._HoTenKhachHang != value))
				{
					this.OnHoTenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._HoTenKhachHang = value;
					this.SendPropertyChanged("HoTenKhachHang");
					this.OnHoTenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT_KhachHang", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string SDT_KhachHang
		{
			get
			{
				return this._SDT_KhachHang;
			}
			set
			{
				if ((this._SDT_KhachHang != value))
				{
					this.OnSDT_KhachHangChanging(value);
					this.SendPropertyChanging();
					this._SDT_KhachHang = value;
					this.SendPropertyChanged("SDT_KhachHang");
					this.OnSDT_KhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoanKhachHang_HoaDonBan", Storage="_HoaDonBans", ThisKey="ID_KhachHang", OtherKey="ID_KhachHang")]
		public EntitySet<HoaDonBan> HoaDonBans
		{
			get
			{
				return this._HoaDonBans;
			}
			set
			{
				this._HoaDonBans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoanKhachHang_Review", Storage="_Reviews", ThisKey="ID_KhachHang", OtherKey="ID_KhachHang")]
		public EntitySet<Review> Reviews
		{
			get
			{
				return this._Reviews;
			}
			set
			{
				this._Reviews.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDonBans(HoaDonBan entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanKhachHang = this;
		}
		
		private void detach_HoaDonBans(HoaDonBan entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanKhachHang = null;
		}
		
		private void attach_Reviews(Review entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanKhachHang = this;
		}
		
		private void detach_Reviews(Review entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoanKhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThamGiaKhuyenMai")]
	public partial class ThamGiaKhuyenMai
	{
		
		private string _ID_KhuyenMai;
		
		private string _ID_SanPham;
		
		private int _GiamGiaSanPham;
		
		private System.Nullable<int> _GiaTruocKhuyenMai;
		
		private System.Nullable<int> _GiaSauKhuyenMai;
		
		public ThamGiaKhuyenMai()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_KhuyenMai", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ID_KhuyenMai
		{
			get
			{
				return this._ID_KhuyenMai;
			}
			set
			{
				if ((this._ID_KhuyenMai != value))
				{
					this._ID_KhuyenMai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SanPham", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string ID_SanPham
		{
			get
			{
				return this._ID_SanPham;
			}
			set
			{
				if ((this._ID_SanPham != value))
				{
					this._ID_SanPham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGiaSanPham", DbType="Int NOT NULL")]
		public int GiamGiaSanPham
		{
			get
			{
				return this._GiamGiaSanPham;
			}
			set
			{
				if ((this._GiamGiaSanPham != value))
				{
					this._GiamGiaSanPham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTruocKhuyenMai", DbType="Int")]
		public System.Nullable<int> GiaTruocKhuyenMai
		{
			get
			{
				return this._GiaTruocKhuyenMai;
			}
			set
			{
				if ((this._GiaTruocKhuyenMai != value))
				{
					this._GiaTruocKhuyenMai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaSauKhuyenMai", DbType="Int")]
		public System.Nullable<int> GiaSauKhuyenMai
		{
			get
			{
				return this._GiaSauKhuyenMai;
			}
			set
			{
				if ((this._GiaSauKhuyenMai != value))
				{
					this._GiaSauKhuyenMai = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinCuaHang")]
	public partial class ThongTinCuaHang
	{
		
		private string _Hotline;
		
		private string _DiaChi;
		
		private string _LienLac;
		
		public ThongTinCuaHang()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hotline", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string Hotline
		{
			get
			{
				return this._Hotline;
			}
			set
			{
				if ((this._Hotline != value))
				{
					this._Hotline = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LienLac", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LienLac
		{
			get
			{
				return this._LienLac;
			}
			set
			{
				if ((this._LienLac != value))
				{
					this._LienLac = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
